// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CountTagsBySubjectEntityID(ctx context.Context, subjectID int64) (int64, error)
	// Optional filters use the ($N::type IS NULL OR col = $N::type) pattern,
	// matching the convention established in users-module/model/queries/user_accounts.sql.
	CreateTag(ctx context.Context, arg CreateTagParams) (Tag, error)
	DeleteTag(ctx context.Context, entityID int64) error
	GetTagByEntityID(ctx context.Context, entityID int64) (Tag, error)
	GetTagByEntityUUID(ctx context.Context, argUuid uuid.UUID) (GetTagByEntityUUIDRow, error)
	ListTagsBySubjectEntityID(ctx context.Context, arg ListTagsBySubjectEntityIDParams) ([]Tag, error)
	SearchTags(ctx context.Context, arg SearchTagsParams) ([]Tag, error)
	UpdateTagColor(ctx context.Context, arg UpdateTagColorParams) error
}

var _ Querier = (*Queries)(nil)
