// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: tags.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countTagsBySubjectEntityID = `-- name: CountTagsBySubjectEntityID :one
SELECT COUNT(*)
FROM tags
WHERE subject_id = $1
`

func (q *Queries) CountTagsBySubjectEntityID(ctx context.Context, subjectID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countTagsBySubjectEntityID, subjectID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createTag = `-- name: CreateTag :one

INSERT INTO tags (entity_id, owner_id, subject_id, purpose, value, color)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING entity_id, owner_id, subject_id, purpose, value, color, created_at, updated_at
`

type CreateTagParams struct {
	EntityID  int64       `json:"entity_id"`
	OwnerID   int64       `json:"owner_id"`
	SubjectID int64       `json:"subject_id"`
	Purpose   string      `json:"purpose"`
	Value     string      `json:"value"`
	Color     pgtype.Text `json:"color"`
}

// Optional filters use the ($N::type IS NULL OR col = $N::type) pattern,
// matching the convention established in users-module/model/queries/user_accounts.sql.
func (q *Queries) CreateTag(ctx context.Context, arg CreateTagParams) (Tag, error) {
	row := q.db.QueryRow(ctx, createTag,
		arg.EntityID,
		arg.OwnerID,
		arg.SubjectID,
		arg.Purpose,
		arg.Value,
		arg.Color,
	)
	var i Tag
	err := row.Scan(
		&i.EntityID,
		&i.OwnerID,
		&i.SubjectID,
		&i.Purpose,
		&i.Value,
		&i.Color,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteTag = `-- name: DeleteTag :exec
DELETE FROM tags
WHERE entity_id = $1
`

func (q *Queries) DeleteTag(ctx context.Context, entityID int64) error {
	_, err := q.db.Exec(ctx, deleteTag, entityID)
	return err
}

const getTagByEntityID = `-- name: GetTagByEntityID :one
SELECT entity_id, owner_id, subject_id, purpose, value, color, created_at, updated_at
FROM tags
WHERE entity_id = $1
`

func (q *Queries) GetTagByEntityID(ctx context.Context, entityID int64) (Tag, error) {
	row := q.db.QueryRow(ctx, getTagByEntityID, entityID)
	var i Tag
	err := row.Scan(
		&i.EntityID,
		&i.OwnerID,
		&i.SubjectID,
		&i.Purpose,
		&i.Value,
		&i.Color,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTagByEntityUUID = `-- name: GetTagByEntityUUID :one
SELECT t.entity_id, t.owner_id, t.subject_id, t.purpose, t.value, t.color,
       t.created_at, t.updated_at, e.uuid
FROM tags t
JOIN entities e ON e.id = t.entity_id
WHERE e.uuid = $1
`

type GetTagByEntityUUIDRow struct {
	EntityID  int64              `json:"entity_id"`
	OwnerID   int64              `json:"owner_id"`
	SubjectID int64              `json:"subject_id"`
	Purpose   string             `json:"purpose"`
	Value     string             `json:"value"`
	Color     pgtype.Text        `json:"color"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	Uuid      uuid.UUID          `json:"uuid"`
}

func (q *Queries) GetTagByEntityUUID(ctx context.Context, argUuid uuid.UUID) (GetTagByEntityUUIDRow, error) {
	row := q.db.QueryRow(ctx, getTagByEntityUUID, argUuid)
	var i GetTagByEntityUUIDRow
	err := row.Scan(
		&i.EntityID,
		&i.OwnerID,
		&i.SubjectID,
		&i.Purpose,
		&i.Value,
		&i.Color,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Uuid,
	)
	return i, err
}

const listTagsBySubjectEntityID = `-- name: ListTagsBySubjectEntityID :many
SELECT entity_id, owner_id, subject_id, purpose, value, color, created_at, updated_at
FROM tags
WHERE subject_id = $1
  AND ($2::text IS NULL OR purpose = $2::text)
ORDER BY created_at ASC
`

type ListTagsBySubjectEntityIDParams struct {
	SubjectID int64  `json:"subject_id"`
	Column2   string `json:"column_2"`
}

func (q *Queries) ListTagsBySubjectEntityID(ctx context.Context, arg ListTagsBySubjectEntityIDParams) ([]Tag, error) {
	rows, err := q.db.Query(ctx, listTagsBySubjectEntityID, arg.SubjectID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tag
	for rows.Next() {
		var i Tag
		if err := rows.Scan(
			&i.EntityID,
			&i.OwnerID,
			&i.SubjectID,
			&i.Purpose,
			&i.Value,
			&i.Color,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchTags = `-- name: SearchTags :many
SELECT entity_id, owner_id, subject_id, purpose, value, color, created_at, updated_at
FROM tags
WHERE ($1::bigint IS NULL OR owner_id = $1::bigint)
  AND ($2::bigint IS NULL OR subject_id = $2::bigint)
  AND ($3::text IS NULL OR purpose = $3::text)
  AND ($4::text IS NULL OR value = $4::text)
ORDER BY created_at ASC
`

type SearchTagsParams struct {
	Column1 int64  `json:"column_1"`
	Column2 int64  `json:"column_2"`
	Column3 string `json:"column_3"`
	Column4 string `json:"column_4"`
}

func (q *Queries) SearchTags(ctx context.Context, arg SearchTagsParams) ([]Tag, error) {
	rows, err := q.db.Query(ctx, searchTags,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Column4,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tag
	for rows.Next() {
		var i Tag
		if err := rows.Scan(
			&i.EntityID,
			&i.OwnerID,
			&i.SubjectID,
			&i.Purpose,
			&i.Value,
			&i.Color,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTagColor = `-- name: UpdateTagColor :exec
UPDATE tags
SET color = $2
WHERE entity_id = $1
`

type UpdateTagColorParams struct {
	EntityID int64       `json:"entity_id"`
	Color    pgtype.Text `json:"color"`
}

func (q *Queries) UpdateTagColor(ctx context.Context, arg UpdateTagColorParams) error {
	_, err := q.db.Exec(ctx, updateTagColor, arg.EntityID, arg.Color)
	return err
}
