// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: tags.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countTagsBySubjectEntityID = `-- name: CountTagsBySubjectEntityID :one
SELECT COUNT(*)
FROM tags t
JOIN accessible_tag_ids_for_actor($1, $2::int[]) acc ON acc.entity_id = t.entity_id
WHERE t.subject_id = $3
`

type CountTagsBySubjectEntityIDParams struct {
	ActorEntityID int64   `json:"actor_entity_id"`
	OpIds         []int32 `json:"op_ids"`
	SubjectID     int64   `json:"subject_id"`
}

func (q *Queries) CountTagsBySubjectEntityID(ctx context.Context, arg CountTagsBySubjectEntityIDParams) (int64, error) {
	row := q.db.QueryRow(ctx, countTagsBySubjectEntityID, arg.ActorEntityID, arg.OpIds, arg.SubjectID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createTag = `-- name: CreateTag :one

INSERT INTO tags (entity_id, owner_id, subject_id, purpose, value, color)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING entity_id, owner_id, subject_id, purpose, value, color, created_at, updated_at
`

type CreateTagParams struct {
	EntityID  int64       `json:"entity_id"`
	OwnerID   int64       `json:"owner_id"`
	SubjectID int64       `json:"subject_id"`
	Purpose   string      `json:"purpose"`
	Value     string      `json:"value"`
	Color     pgtype.Text `json:"color"`
}

// Optional filters use the (sqlc.narg('name')::type IS NULL OR col = sqlc.narg('name')::type)
// pattern so the generated params struct has readable, nullable field names (pgtype.Text,
// pgtype.Int8, etc.) instead of positional Column1/Column2 names.
func (q *Queries) CreateTag(ctx context.Context, arg CreateTagParams) (Tag, error) {
	row := q.db.QueryRow(ctx, createTag,
		arg.EntityID,
		arg.OwnerID,
		arg.SubjectID,
		arg.Purpose,
		arg.Value,
		arg.Color,
	)
	var i Tag
	err := row.Scan(
		&i.EntityID,
		&i.OwnerID,
		&i.SubjectID,
		&i.Purpose,
		&i.Value,
		&i.Color,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteTag = `-- name: DeleteTag :exec
DELETE FROM tags
WHERE entity_id = $1
`

func (q *Queries) DeleteTag(ctx context.Context, entityID int64) error {
	_, err := q.db.Exec(ctx, deleteTag, entityID)
	return err
}

const getTagByEntityID = `-- name: GetTagByEntityID :one
SELECT entity_id, owner_id, subject_id, purpose, value, color, created_at, updated_at
FROM tags
WHERE entity_id = $1
`

func (q *Queries) GetTagByEntityID(ctx context.Context, entityID int64) (Tag, error) {
	row := q.db.QueryRow(ctx, getTagByEntityID, entityID)
	var i Tag
	err := row.Scan(
		&i.EntityID,
		&i.OwnerID,
		&i.SubjectID,
		&i.Purpose,
		&i.Value,
		&i.Color,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTagByEntityUUID = `-- name: GetTagByEntityUUID :one
SELECT t.entity_id, t.owner_id, t.subject_id, t.purpose, t.value, t.color,
       t.created_at, t.updated_at, e.uuid
FROM tags t
JOIN entities e ON e.id = t.entity_id
WHERE e.uuid = $1
`

type GetTagByEntityUUIDRow struct {
	EntityID  int64              `json:"entity_id"`
	OwnerID   int64              `json:"owner_id"`
	SubjectID int64              `json:"subject_id"`
	Purpose   string             `json:"purpose"`
	Value     string             `json:"value"`
	Color     pgtype.Text        `json:"color"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	Uuid      uuid.UUID          `json:"uuid"`
}

func (q *Queries) GetTagByEntityUUID(ctx context.Context, argUuid uuid.UUID) (GetTagByEntityUUIDRow, error) {
	row := q.db.QueryRow(ctx, getTagByEntityUUID, argUuid)
	var i GetTagByEntityUUIDRow
	err := row.Scan(
		&i.EntityID,
		&i.OwnerID,
		&i.SubjectID,
		&i.Purpose,
		&i.Value,
		&i.Color,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Uuid,
	)
	return i, err
}

const listTagsBySubjectEntityID = `-- name: ListTagsBySubjectEntityID :many
SELECT t.entity_id, t.owner_id, t.subject_id, t.purpose, t.value, t.color,
       t.created_at, t.updated_at, e.uuid
FROM tags t
JOIN entities e ON e.id = t.entity_id
JOIN accessible_tag_ids_for_actor($1, $2::int[]) acc ON acc.entity_id = t.entity_id
WHERE t.subject_id = $3
  AND ($4::text IS NULL OR t.purpose = $4::text)
ORDER BY t.created_at ASC
LIMIT $6 OFFSET $5
`

type ListTagsBySubjectEntityIDParams struct {
	ActorEntityID int64       `json:"actor_entity_id"`
	OpIds         []int32     `json:"op_ids"`
	SubjectID     int64       `json:"subject_id"`
	Purpose       pgtype.Text `json:"purpose"`
	Offset        int32       `json:"offset"`
	Limit         int32       `json:"limit"`
}

type ListTagsBySubjectEntityIDRow struct {
	EntityID  int64              `json:"entity_id"`
	OwnerID   int64              `json:"owner_id"`
	SubjectID int64              `json:"subject_id"`
	Purpose   string             `json:"purpose"`
	Value     string             `json:"value"`
	Color     pgtype.Text        `json:"color"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	Uuid      uuid.UUID          `json:"uuid"`
}

func (q *Queries) ListTagsBySubjectEntityID(ctx context.Context, arg ListTagsBySubjectEntityIDParams) ([]ListTagsBySubjectEntityIDRow, error) {
	rows, err := q.db.Query(ctx, listTagsBySubjectEntityID,
		arg.ActorEntityID,
		arg.OpIds,
		arg.SubjectID,
		arg.Purpose,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTagsBySubjectEntityIDRow
	for rows.Next() {
		var i ListTagsBySubjectEntityIDRow
		if err := rows.Scan(
			&i.EntityID,
			&i.OwnerID,
			&i.SubjectID,
			&i.Purpose,
			&i.Value,
			&i.Color,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Uuid,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchTags = `-- name: SearchTags :many
SELECT t.entity_id, t.owner_id, t.subject_id, t.purpose, t.value, t.color,
       t.created_at, t.updated_at, e.uuid
FROM tags t
JOIN entities e ON e.id = t.entity_id
JOIN accessible_tag_ids_for_actor($1, $2::int[]) acc ON acc.entity_id = t.entity_id
WHERE ($3::bigint IS NULL OR t.owner_id = $3::bigint)
  AND ($4::bigint IS NULL OR t.subject_id = $4::bigint)
  AND ($5::text IS NULL OR t.purpose = $5::text)
  AND ($6::text IS NULL OR t.value = $6::text)
ORDER BY t.created_at ASC
LIMIT $8 OFFSET $7
`

type SearchTagsParams struct {
	ActorEntityID int64       `json:"actor_entity_id"`
	OpIds         []int32     `json:"op_ids"`
	OwnerID       pgtype.Int8 `json:"owner_id"`
	SubjectID     pgtype.Int8 `json:"subject_id"`
	Purpose       pgtype.Text `json:"purpose"`
	Value         pgtype.Text `json:"value"`
	Offset        int32       `json:"offset"`
	Limit         int32       `json:"limit"`
}

type SearchTagsRow struct {
	EntityID  int64              `json:"entity_id"`
	OwnerID   int64              `json:"owner_id"`
	SubjectID int64              `json:"subject_id"`
	Purpose   string             `json:"purpose"`
	Value     string             `json:"value"`
	Color     pgtype.Text        `json:"color"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	Uuid      uuid.UUID          `json:"uuid"`
}

func (q *Queries) SearchTags(ctx context.Context, arg SearchTagsParams) ([]SearchTagsRow, error) {
	rows, err := q.db.Query(ctx, searchTags,
		arg.ActorEntityID,
		arg.OpIds,
		arg.OwnerID,
		arg.SubjectID,
		arg.Purpose,
		arg.Value,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchTagsRow
	for rows.Next() {
		var i SearchTagsRow
		if err := rows.Scan(
			&i.EntityID,
			&i.OwnerID,
			&i.SubjectID,
			&i.Purpose,
			&i.Value,
			&i.Color,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Uuid,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTagColor = `-- name: UpdateTagColor :one
UPDATE tags
SET color = $1
WHERE entity_id = $2
RETURNING entity_id, owner_id, subject_id, purpose, value, color, created_at, updated_at
`

type UpdateTagColorParams struct {
	Color    pgtype.Text `json:"color"`
	EntityID int64       `json:"entity_id"`
}

func (q *Queries) UpdateTagColor(ctx context.Context, arg UpdateTagColorParams) (Tag, error) {
	row := q.db.QueryRow(ctx, updateTagColor, arg.Color, arg.EntityID)
	var i Tag
	err := row.Scan(
		&i.EntityID,
		&i.OwnerID,
		&i.SubjectID,
		&i.Purpose,
		&i.Value,
		&i.Color,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
